<?php

namespace Database\Seeders;

use App\Models\Product;
use App\Models\Category;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run()
    {
        $categories = Category::all();
        
        $allProducts = [
            // ========== ELECTRONICS ==========
            [
                'name' => 'iPhone 14 Pro',
                'slug' => 'iphone-14-pro',
                'description' => 'Latest smartphone with advanced camera',
                'price' => 89999,
                'old_price' => 99999,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Apple',
                'image' => 'iphone.jpg',
                'rating' => 4.9,
                'reviews' => 256,
                'discount' => 10,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Samsung QLED TV',
                'slug' => 'samsung-qled-tv',
                'description' => '65" 4K Smart TV with Quantum HDR',
                'price' => 119999,
                'old_price' => 149999,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Samsung',
                'image' => 'tv.jpg',
                'rating' => 4.7,
                'reviews' => 189,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => false,
                'is_new' => false
            ],
            [
                'name' => 'MacBook Air M2',
                'slug' => 'macbook-air-m2',
                'description' => 'Lightweight laptop with M2 chip',
                'price' => 109999,
                'old_price' => 124999,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Apple',
                'image' => 'macbook.jpg',
                'rating' => 4.8,
                'reviews' => 312,
                'discount' => 12,
                'stock' => 'low',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Sony WH-1000XM4',
                'slug' => 'sony-wh-1000xm4',
                'description' => 'Noise cancelling wireless headphones',
                'price' => 28999,
                'old_price' => 34999,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Sony',
                'image' => 'sony-headphones.jpg',
                'rating' => 4.9,
                'reviews' => 432,
                'discount' => 17,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'HomePod mini',
                'slug' => 'homepod-mini',
                'description' => 'Smart speaker with immersive sound',
                'price' => 23900,
                'old_price' => 29900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Apple',
                'image' => 'homepod.jpg',
                'rating' => 4.8,
                'reviews' => 121,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => false,
                'is_new' => false
            ],
            [
                'name' => 'Wireless Earbuds Pro',
                'slug' => 'wireless-earbuds-pro',
                'description' => 'Active noise cancellation, 30hr battery',
                'price' => 17900,
                'old_price' => 19900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'SoundCore',
                'image' => 'wireless-earbuds.jpg',
                'rating' => 4.7,
                'reviews' => 234,
                'discount' => 10,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Gaming Keyboard',
                'slug' => 'gaming-keyboard',
                'description' => 'Mechanical RGB backlit keyboard',
                'price' => 8900,
                'old_price' => 10900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Razer',
                'image' => 'gaming-keyboard.jpg',
                'rating' => 4.5,
                'reviews' => 189,
                'discount' => 18,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Smart Home Camera',
                'slug' => 'smart-home-camera',
                'description' => '360° view, night vision, motion detection',
                'price' => 12900,
                'old_price' => 14900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Ring',
                'image' => 'smart-camera.jpg',
                'rating' => 4.6,
                'reviews' => 312,
                'discount' => 13,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => true
            ],
            [
                'name' => 'Portable Speaker',
                'slug' => 'portable-speaker',
                'description' => 'Waterproof, 20hr battery life',
                'price' => 11900,
                'old_price' => 13900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'JBL',
                'image' => 'portable-speaker.jpg',
                'rating' => 4.8,
                'reviews' => 198,
                'discount' => 14,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => '4K Action Camera',
                'slug' => '4k-action-camera',
                'description' => 'Waterproof, image stabilization',
                'price' => 24900,
                'old_price' => 29900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'GoPro',
                'image' => 'action-camera.jpg',
                'rating' => 4.6,
                'reviews' => 178,
                'discount' => 17,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Drone with Camera',
                'slug' => 'drone-with-camera',
                'description' => '4K video, 30min flight time',
                'price' => 39900,
                'old_price' => 49900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'DJI',
                'image' => 'drone.jpg',
                'rating' => 4.8,
                'reviews' => 156,
                'discount' => 20,
                'stock' => 'low',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => true
            ],
            [
                'name' => 'Wireless Mouse Pro',
                'slug' => 'wireless-mouse-pro',
                'description' => 'Ergonomic design with silent clicks',
                'price' => 3900,
                'old_price' => 4900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Logitech',
                'image' => 'wireless-mouse.jpg',
                'rating' => 4.5,
                'reviews' => 89,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => false,
                'is_new' => true
            ],
            [
                'name' => 'Smart Watch Series 5',
                'slug' => 'smart-watch-series-5',
                'description' => 'Health monitoring & notifications',
                'price' => 29900,
                'old_price' => 34900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Apple',
                'image' => 'smart-watch.jpg',
                'rating' => 4.9,
                'reviews' => 234,
                'discount' => 14,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Noise Cancelling Earbuds',
                'slug' => 'noise-cancelling-earbuds',
                'description' => 'Wireless with 30hr battery life',
                'price' => 12900,
                'old_price' => 15900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Bose',
                'image' => 'earbuds.jpg',
                'rating' => 4.7,
                'reviews' => 156,
                'discount' => 19,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => true
            ],
            [
                'name' => 'Fitness Tracker',
                'slug' => 'fitness-tracker',
                'description' => 'Heart rate monitor, sleep tracking',
                'price' => 7900,
                'old_price' => 9900,
                'category_id' => $categories->where('slug', 'electronics')->first()->id,
                'brand' => 'Fitbit',
                'image' => 'fitness-tracker.jpg',
                'rating' => 4.4,
                'reviews' => 423,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== FASHION ==========
            [
                'name' => 'Nike Air Max',
                'slug' => 'nike-air-max',
                'description' => 'Premium running shoes with air cushion',
                'price' => 12999,
                'old_price' => 16999,
                'category_id' => $categories->where('slug', 'fashion')->first()->id,
                'brand' => 'Nike',
                'image' => 'nike-shoes.jpg',
                'rating' => 4.6,
                'reviews' => 89,
                'discount' => 24,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Designer Handbag',
                'slug' => 'designer-handbag',
                'description' => 'Genuine leather, waterproof',
                'price' => 24999,
                'old_price' => 34999,
                'category_id' => $categories->where('slug', 'fashion')->first()->id,
                'brand' => 'Michael Kors',
                'image' => 'designer-handbag.jpg',
                'rating' => 4.9,
                'reviews' => 98,
                'discount' => 29,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => true
            ],
            [
                'name' => 'Adidas Sneakers',
                'slug' => 'adidas-sneakers',
                'description' => 'x Sean Wotherspoon Superstar sneakers',
                'price' => 15900,
                'old_price' => 19900,
                'category_id' => $categories->where('slug', 'fashion')->first()->id,
                'brand' => 'Adidas',
                'image' => 'adidas-sneakers.jpg',
                'rating' => 4.7,
                'reviews' => 156,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Gucci Handbag',
                'slug' => 'gucci-handbag',
                'description' => 'Premium designer handbag with leather finish',
                'price' => 45900,
                'old_price' => 59900,
                'category_id' => $categories->where('slug', 'fashion')->first()->id,
                'brand' => 'Gucci',
                'image' => 'handbag.jpg',
                'rating' => 4.8,
                'reviews' => 78,
                'discount' => 23,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Premium Shirt',
                'slug' => 'premium-shirt',
                'description' => '100% cotton formal shirt',
                'price' => 3999,
                'old_price' => 4999,
                'category_id' => $categories->where('slug', 'fashion')->first()->id,
                'brand' => 'Van Heusen',
                'image' => 'shirt.jpg',
                'rating' => 4.5,
                'reviews' => 67,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => false,
                'is_new' => true
            ],

            // ========== HOME & KITCHEN ==========
            [
                'name' => 'KitchenAid Mixer',
                'slug' => 'kitchenaid-mixer',
                'description' => 'Professional stand mixer, 5-quart',
                'price' => 44999,
                'old_price' => 54999,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'KitchenAid',
                'image' => 'kitchenaid.jpg',
                'rating' => 4.8,
                'reviews' => 203,
                'discount' => 18,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => false,
                'is_new' => false
            ],
            [
                'name' => 'Coffee Maker Deluxe',
                'slug' => 'coffee-maker-deluxe',
                'description' => 'Programmable, 12-cup capacity',
                'price' => 15999,
                'old_price' => 19999,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'Breville',
                'image' => 'coffee-maker.jpg',
                'rating' => 4.7,
                'reviews' => 267,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Modern Leather Sofa',
                'slug' => 'modern-leather-sofa',
                'description' => '3 seater sofa with premium leather',
                'price' => 45999,
                'old_price' => 59999,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'Ashley',
                'image' => 'sofa.jpg',
                'rating' => 4.4,
                'reviews' => 156,
                'discount' => 23,
                'stock' => 'low',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Dyson V11 Vacuum',
                'slug' => 'dyson-v11-vacuum',
                'description' => 'Cordless vacuum with powerful suction',
                'price' => 59900,
                'old_price' => 69900,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'Dyson',
                'image' => 'dyson.jpg',
                'rating' => 4.7,
                'reviews' => 167,
                'discount' => 14,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Air Purifier',
                'slug' => 'air-purifier',
                'description' => 'HEPA filter, smart sensor',
                'price' => 19900,
                'old_price' => 24900,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'Blueair',
                'image' => 'air-purifier.jpg',
                'rating' => 4.5,
                'reviews' => 234,
                'discount' => 20,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Laptop Sleeve MacBook',
                'slug' => 'laptop-sleeve-macbook',
                'description' => 'Organic Cotton, fairtrade certified',
                'price' => 5900,
                'old_price' => 6900,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'Incase',
                'image' => 'laptop-sleeve.jpg',
                'rating' => 4.8,
                'reviews' => 121,
                'discount' => 14,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => false,
                'is_new' => true
            ],
            [
                'name' => 'Bug Book',
                'slug' => 'bug-book',
                'description' => 'Educational book about insects',
                'price' => 990,
                'old_price' => 1490,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'National Geographic',
                'image' => 'bug-book.jpg',
                'rating' => 4.6,
                'reviews' => 89,
                'discount' => 33,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => false,
                'is_new' => false
            ],
            [
                'name' => 'Furniture Village Collection',
                'slug' => 'furniture-village-collection',
                'description' => 'Premium furniture collection with modern designs',
                'price' => 89999,
                'old_price' => 119999,
                'category_id' => $categories->where('slug', 'home-kitchen')->first()->id,
                'brand' => 'West Elm',
                'image' => 'furniture-village.jpg',
                'rating' => 4.7,
                'reviews' => 234,
                'discount' => 25,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== SPORTS & FITNESS ==========
            [
                'name' => 'Yoga Mat Premium',
                'slug' => 'yoga-mat-premium',
                'description' => 'Non-slip, eco-friendly material',
                'price' => 2499,
                'old_price' => 3499,
                'category_id' => $categories->where('slug', 'sports-fitness')->first()->id,
                'brand' => 'Manduka',
                'image' => 'yoga-mat.jpg',
                'rating' => 4.8,
                'reviews' => 156,
                'discount' => 29,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => true
            ],
            [
                'name' => 'Fashion World Collection',
                'slug' => 'fashion-world-collection',
                'description' => 'Latest fashion trends for all seasons',
                'price' => 39999,
                'old_price' => 54999,
                'category_id' => $categories->where('slug', 'sports-fitness')->first()->id,
                'brand' => 'Zara',
                'image' => 'fashion-world.jpg',
                'rating' => 4.6,
                'reviews' => 189,
                'discount' => 27,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Sneakers Pro',
                'slug' => 'sneakers-pro',
                'description' => 'Professional running shoes with cushion technology',
                'price' => 12900,
                'old_price' => 16900,
                'category_id' => $categories->where('slug', 'sports-fitness')->first()->id,
                'brand' => 'Under Armour',
                'image' => 'sneakers.jpg',
                'rating' => 4.7,
                'reviews' => 256,
                'discount' => 24,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== BOOKS ==========
            [
                'name' => 'Atomic Habits Book',
                'slug' => 'atomic-habits-book',
                'description' => 'Build good habits and break bad ones',
                'price' => 499,
                'old_price' => 699,
                'category_id' => $categories->where('slug', 'books')->first()->id,
                'brand' => 'Penguin',
                'image' => 'atomic-habits.jpg',
                'rating' => 4.8,
                'reviews' => 1256,
                'discount' => 29,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => false,
                'is_new' => false
            ],
            [
                'name' => 'Best Seller Book Collection',
                'slug' => 'best-seller-book-collection',
                'description' => 'Collection of 5 best-selling books',
                'price' => 2499,
                'old_price' => 3499,
                'category_id' => $categories->where('slug', 'books')->first()->id,
                'brand' => 'Penguin Classics',
                'image' => 'books.jpg',
                'rating' => 4.9,
                'reviews' => 456,
                'discount' => 29,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Travel Guide Book',
                'slug' => 'travel-guide-book',
                'description' => 'Complete travel guide with maps and tips',
                'price' => 1299,
                'old_price' => 1799,
                'category_id' => $categories->where('slug', 'books')->first()->id,
                'brand' => 'Lonely Planet',
                'image' => 'travel.jpg',
                'rating' => 4.7,
                'reviews' => 189,
                'discount' => 28,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== BEAUTY & HEALTH ==========
            [
                'name' => 'Complete Skincare Set',
                'slug' => 'complete-skincare-set',
                'description' => '5 piece skincare routine set',
                'price' => 2999,
                'old_price' => 4999,
                'category_id' => $categories->where('slug', 'beauty-health')->first()->id,
                'brand' => 'Cetaphil',
                'image' => 'skincare-set.jpg',
                'rating' => 4.5,
                'reviews' => 89,
                'discount' => 40,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => false,
                'is_new' => false
            ],
            [
                'name' => 'Electric Toothbrush',
                'slug' => 'electric-toothbrush',
                'description' => 'Smart pressure sensor, 4 modes',
                'price' => 8900,
                'old_price' => 11900,
                'category_id' => $categories->where('slug', 'beauty-health')->first()->id,
                'brand' => 'Oral-B',
                'image' => 'electric-toothbrush.jpg',
                'rating' => 4.7,
                'reviews' => 345,
                'discount' => 25,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== TOYS & GAMES ==========
            [
                'name' => 'Instax Mini 11',
                'slug' => 'instax-mini-11',
                'description' => 'Selfie mode and selfie mirror, Macro mode',
                'price' => 8900,
                'old_price' => 9900,
                'category_id' => $categories->where('slug', 'toys-games')->first()->id,
                'brand' => 'Fujifilm',
                'image' => 'instax-mini.jpg',
                'rating' => 4.8,
                'reviews' => 121,
                'discount' => 10,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => false,
                'is_new' => false
            ],

            // ========== AUTOMOTIVE ==========
            [
                'name' => 'Hand Watch',
                'slug' => 'hand-watch',
                'description' => 'Citizen 650M, W-69g',
                'price' => 5900,
                'old_price' => 6900,
                'category_id' => $categories->where('slug', 'automotive')->first()->id,
                'brand' => 'Citizen',
                'image' => 'watch.jpg',
                'rating' => 4.6,
                'reviews' => 89,
                'discount' => 14,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],
            [
                'name' => 'Pendleton Water Bottle',
                'slug' => 'pendleton-water-bottle',
                'description' => 'Stainless steel, Food safe, Hand wash',
                'price' => 8900,
                'old_price' => 9900,
                'category_id' => $categories->where('slug', 'automotive')->first()->id,
                'brand' => 'Hydro Flask',
                'image' => 'water-bottle.jpg',
                'rating' => 4.9,
                'reviews' => 203,
                'discount' => 10,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => false,
                'is_new' => false
            ],

            // ========== TRAVEL ==========
            [
                'name' => 'Travel Backpack Pro',
                'slug' => 'travel-backpack-pro',
                'description' => 'Waterproof travel backpack with laptop compartment',
                'price' => 4599,
                'old_price' => 5999,
                'category_id' => $categories->where('slug', 'travel')->first()->id,
                'brand' => 'Osprey',
                'image' => 'travel-bag.jpg',
                'rating' => 4.7,
                'reviews' => 134,
                'discount' => 23,
                'stock' => 'available',
                'is_best_seller' => false,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== FURNITURE ==========
            [
                'name' => 'Modern Furniture Set',
                'slug' => 'modern-furniture-set',
                'description' => 'Complete modern furniture set for living room',
                'price' => 89999,
                'old_price' => 119999,
                'category_id' => $categories->where('slug', 'furniture')->first()->id,
                'brand' => 'IKEA',
                'image' => 'furniture.jpg',
                'rating' => 4.8,
                'reviews' => 189,
                'discount' => 25,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],

            // ========== TECHNOLOGY ==========
            [
                'name' => 'Tech Gadgets Bundle',
                'slug' => 'tech-gadgets-bundle',
                'description' => 'Bundle of latest tech gadgets',
                'price' => 29999,
                'old_price' => 39999,
                'category_id' => $categories->where('slug', 'technology')->first()->id,
                'brand' => 'Anker',
                'image' => 'tech.jpg',
                'rating' => 4.7,
                'reviews' => 278,
                'discount' => 25,
                'stock' => 'available',
                'is_best_seller' => true,
                'is_trending' => true,
                'is_new' => false
            ],
        ];

        foreach ($allProducts as $productData) {
            // Use updateOrCreate to avoid duplicates
            Product::updateOrCreate(
                ['slug' => $productData['slug']], // Check by slug
                $productData // Update or create with this data
            );
        }

        // Update category product counts
        $categories = Category::all();
        foreach ($categories as $category) {
            $category->product_count = $category->products()->count();
            $category->save();
        }

        $this->command->info(count($allProducts) . ' unique products seeded successfully!');
        $this->command->info('Category product counts updated.');
    }
}